CREATE TABLE IF NOT EXISTS reset_password (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);